apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker.io/zeongiii/nyamnyam-config-server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: git@github.com:zeongii/nyamnyam-secret-server.git
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-credentials
                  key: privateKey
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_HOST_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-credentials
                  key: hostKey
            - name: SPRING_CLOUD_CONFIG_SERVER_ENCRYPT_ENABLED
              value: "false"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: config-server
      imagePullSecrets:
        - name: nyamnyam-regcred