---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker.io/zeongiii/nyamnyam-config-server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /app/config  # 설정 파일을 마운트할 경로
      volumes:
        - name: config-volume
          configMap:
            name: config-server
      imagePullSecrets:
        - name: nyamnyam-regcred  # 이미지 풀 비밀 이름, 맞는지 확인
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: nyamnyam
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30797
  selector:
    app: config-server