---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: docker.io/zeongiii/nyamnyam-eureka-server:1.1
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config  # 설정 파일을 마운트할 경로
      volumes:
        - name: config-volume
          configMap:
            name: eureka-server
      imagePullSecrets:
        - name: nyamnyam-regcred  # 이미지 풀 비밀 이름, 맞는지 확인
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: nyamnyam
spec:
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
  type: LoadBalancer
