apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: docker.io/zeongiii/nyamnyam-chat-service:1.1
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "chat-service"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "chat-service:${server.port}"
      volumes:
        - name: config-volume
          configMap:
            name: chat-service
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: nyamnyam
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  selector:
    app: chat-service

