---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: docker.io/zeongiii/nyamnyam-gateway-server:1.0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "gateway-server"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "gateway-server:${server.port}"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config

      volumes:
        - name: config-volume
          configMap:
            name: gateway-server
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: nyamnyam
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-ssl-certificate-no: "34169"
    service.beta.kubernetes.io/ncloud-load-balancer-tls-ports: "443"
spec:
  type: LoadBalancer  # LoadBalancer 타입으로 설정
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: gateway-server
