---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: docker.io/zeongii/nyamnyam-gateway-server:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: gateway-server
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: nyamnyam
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30496
  selector:
    app: gateway-server