---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: docker.io/zeongii/nyamnyam-gateway-server:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SPRING_CLOUD_CONFIG_URI
              value: optional:configserver:http://211.188.55.210:8888/gateway-server/prod
            - name: SPRING_APPLICATION_NAME
              value: gateway-server
          volumeMounts:
            - name: gateway-volume
              mountPath: /app/config
      volumes:
        - name: gateway-volume
          configMap:
            name: gateway-server
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: nyamnyam
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: gateway-server