apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyamnyam-api-ingress
  namespace: nyamnyam
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nyamnyam.kr
      http:
        paths:
          - path: nyamnyam-gateway-server-d59fa-100204856-de2b39d996c7.kr.lb.naverncp.com
            pathType: Prefix
            backend:
              service:
                name: gateway-server
                port:
                  number: 8000