apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: docker.io/zeongiii/nyamnyam-user-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 800Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
      volumes:
        - name: config-volume
          configMap:
            name: user-service
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-stable
  namespace: nyamnyam
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: user-service