apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: docker.io/zeongiii/nyamnyam-post-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 800Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: post-service
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-stable
  namespace: nyamnyam
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: post-service